sudo: false
language: python
env:
  - ANSIBLE_VERSION=2.5.15
  - ANSIBLE_VERSION=2.7.7
install:
  - pip install flask==0.10
  - pip install ansible==${ANSIBLE_VERSION}
script:
  - python -m unittest discover
